### ISSUE TITLE
 --prereq option is not working

### ISSUE THREAD

**Issue by KnightofWhite** [assarbad/build-asuswrt-merlin#2]
I have an issue with first script run.
When i try to start script with --prereq option i get error 
Ubuntu x64 12.04.5

```
root@ubuntu:~/asuswrt-merlin# ./ubuntu-build-image --prereq
ERROR: unrecognized router model --prereq. Either the command line or this script needs fixing.
```

**Comment by assarbad** [comment]
Thanks for the report. I'll look into it. You ran the latest from `master`?

**Comment by assarbad** [comment]
Okay, check whether this is now fixed on master. I think the problem was that it matched anything with `--prereq` plus any characters, but not 0 or more characters.

This should be fixed now. You can also use `-P` as a shorthand.

**Comment by assarbad** [comment]
Added this to the `README.md`.

**Comment by KnightofWhite** [comment]
Ok, first step is passed by apply -P option, all packeges are installed on my system.
One question about confirm packages install , better enter "Y" instead of "Yes" or just hit Enter for approve or CTRL+C for exit
 Second step start a compilation .... but ...

```
root@ubuntu:~/asuswrt-merlin# ./ubuntu-build-image RT-N66U                   
NOTE: this script has only been tested on Ubuntu 14.04. If you run it on a different platform, please report back if it works. But more importantly report back if it doesn't. Thanks.
dpkg-query: error: unknown option --load-avail

Use --help for help about querying packages.
ERROR: it appears you have packages missing (see above) that are required to build a firmware image.
Use:
        ./ubuntu-build-image --prereq
or:
        apt-get --no-install-recommends install ...
to install the missing packages, then retry.
root@ubuntu:~/asuswrt-merlin#
```

**Comment by assarbad** [comment]
Oh, snap. So this means that this option is new. I'll have to try on Ubuntu 12.04.5 myself and will then see what can be done. For now I'll commit a little workaround shortly. What it does is to give you the full command line with `apt-get install` ... you'll have to perform that step manually nevertheless, until I have devised a solution on `precise`.

I'll see about the suggestion regarding Y/N etc as well. I was trying to dodge that, because it complicates the script unnecessarily.

**Comment by assarbad** [comment]
This should now be solved. I am currently running the test on 12.04. So far all looks fine. Tested on Debian already.

**Comment by assarbad** [comment]
Worked like a charm on Ubuntu 12.04, 14.04 and Debian 7.8
